ALTER TABLE `calls` MODIFY COLUMN `status` enum('EM ANDAMENTO','AGUARDANDO PP','AGUARDANDO ORÇAMENTO','AGUARDANDO SEGURADORA','ZURICH','FINALIZADO','TROCA','RECUSADO') NOT NULL DEFAULT 'EM ANDAMENTO';
UPDATE `calls` SET `status` = 'ZURICH' WHERE `status` = 'AGUARDANDO SEGURADORA';
UPDATE `history` SET `statusAnterior` = 'ZURICH' WHERE `statusAnterior` = 'AGUARDANDO SEGURADORA';
UPDATE `history` SET `statusNovo` = 'ZURICH' WHERE `statusNovo` = 'AGUARDANDO SEGURADORA';
UPDATE `history` SET `evento` = REPLACE(REPLACE(`evento`, 'Seguradora', 'ZURICH'), 'seguradora', 'ZURICH') WHERE `evento` LIKE '%seguradora%' OR `evento` LIKE '%Seguradora%';
ALTER TABLE `calls` MODIFY COLUMN `status` enum('EM ANDAMENTO','AGUARDANDO PP','AGUARDANDO ORÇAMENTO','ZURICH','FINALIZADO','TROCA','RECUSADO') NOT NULL DEFAULT 'EM ANDAMENTO';
