import React from "react";
import { Input } from "@/components/ui/input";
import { Search, ChevronRight, Wrench } from "lucide-react";
import { useState } from "react";
import { useLocation } from "wouter";
import { trpc } from "@/lib/trpc";

export function matchesCallSearch(call: { numeroOs?: string; serial?: string }, term: string) { const value = term.trim().toLowerCase(); if (!value) return true; return `${call.numeroOs || ""} ${call.serial || ""}`.toLowerCase().includes(value); }

const statusClass: Record<string, string> = { "EM ANDAMENTO": "bg-blue-50 text-blue-700 border-blue-200", "AGUARDANDO PP": "bg-amber-50 text-amber-700 border-amber-200", "AGUARDANDO ORÇAMENTO": "bg-violet-50 text-violet-700 border-violet-200", "AGUARDANDO SEGURADORA": "bg-rose-50 text-rose-700 border-rose-200", FINALIZADO: "bg-emerald-50 text-emerald-700 border-emerald-200", TROCA: "bg-slate-100 text-slate-700 border-slate-200", RECUSADO: "bg-red-50 text-red-700 border-red-200" };

export default function CallSearch() {
  const [search, setSearch] = useState("");
  const [, setLocation] = useLocation();
  const { data: calls = [], isLoading } = trpc.calls.list.useQuery({ search: search.trim() || undefined }, { refetchInterval: 10000, refetchOnWindowFocus: true });
  return <div className="p-6 lg:p-8"><div className="mx-auto max-w-[1300px]"><p className="text-sm font-medium text-[#e09f18]">Consulta operacional</p><h1 className="mt-1 text-3xl font-bold text-slate-900">Chamados</h1><p className="mt-1 text-sm text-slate-500">Pesquise rapidamente por número de O.S. ou serial para abrir os detalhes.</p><div className="mt-7 rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div className="relative max-w-2xl"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><Input autoFocus value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Digite a O.S. ou o serial..." className="h-12 border-0 bg-slate-50 pl-10 text-base shadow-none focus-visible:ring-1"/></div></div><div className="mt-5 overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm">{isLoading ? <div className="p-12 text-center text-sm text-slate-400">Buscando chamados...</div> : calls.length === 0 ? <div className="p-14 text-center"><Wrench className="mx-auto h-9 w-9 text-slate-300"/><p className="mt-3 font-medium text-slate-600">Nenhum chamado encontrado</p><p className="mt-1 text-xs text-slate-400">A busca considera número de O.S. e serial.</p></div> : <div className="divide-y divide-slate-100">{calls.filter((call: any) => matchesCallSearch(call, search)).map((call: any) => <button key={call.id} onClick={() => setLocation(`/?call=${call.id}`)} className="flex w-full items-center gap-4 p-5 text-left transition hover:bg-slate-50"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className="font-mono text-sm font-semibold text-slate-900">{call.numeroOs}</span><span className={`rounded-full border px-2.5 py-1 text-[11px] font-semibold ${statusClass[call.status] || "bg-slate-50 text-slate-600"}`}>{call.status}</span></div><p className="mt-1 text-sm text-slate-700">{call.modelo}</p><p className="mt-1 truncate text-xs text-slate-400">Serial {call.serial} · {call.queixa}</p></div><div className="hidden text-right sm:block"><p className="text-sm font-semibold text-slate-800">{call.dataFinalizacao ? "Encerrado" : "Aberto"}</p><p className="text-xs text-slate-400">{new Date(call.dataEntrada).toLocaleDateString()}</p></div><ChevronRight className="h-4 w-4 text-slate-300"/></button>)}</div>}</div></div></div>;
}
