import { Input } from "@/components/ui/input";
import { Search, RefreshCcw, FileWarning } from "lucide-react";
import { useState } from "react";
import { trpc } from "@/lib/trpc";

export default function HistoricalCalls({ kind }: { kind: "TROCA" | "RECUSADO" }) {
  const [search, setSearch] = useState("");
  const isTroca = kind === "TROCA";
  const troca = trpc.historical.troca.useQuery({ search: search || undefined }, { refetchInterval: 15000, enabled: isTroca });
  const recusado = trpc.historical.recusado.useQuery({ search: search || undefined }, { refetchInterval: 15000, enabled: !isTroca });
  const data = (isTroca ? troca.data : recusado.data) || [];
  const isLoading = isTroca ? troca.isLoading : recusado.isLoading;
  const EmptyIcon = isTroca ? RefreshCcw : FileWarning;
  return <div className="p-6 lg:p-8"><div className="mx-auto max-w-[1500px]"><div className="flex items-end justify-between gap-4"><div><p className="text-sm font-medium text-[#e09f18]">Consulta histórica</p><h1 className="mt-1 text-3xl font-bold text-slate-900">{isTroca ? "Trocas" : "Orçamentos recusados"}</h1><p className="mt-1 text-sm text-slate-500">Registros encerrados para consulta, sem misturar com a operação ativa.</p></div><span className="rounded-full bg-slate-100 px-3 py-1.5 text-xs font-semibold text-slate-600">{data.length} registros</span></div><div className="mt-7 rounded-xl border border-slate-200 bg-white p-3 shadow-sm"><div className="relative max-w-xl"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><Input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Pesquisar por O.S. ou serial..." className="h-10 border-0 bg-slate-50 pl-10 shadow-none"/></div></div><div className="mt-5 overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">O.S.</th><th className="px-5 py-3">Serial</th><th className="px-5 py-3">Modelo</th><th className="px-5 py-3">Queixa</th><th className="px-5 py-3">Entrada</th><th className="px-5 py-3">{isTroca ? "Encaminhado para troca" : "Data da recusa"}</th><th className="px-5 py-3">Origem</th></tr></thead><tbody className="divide-y divide-slate-100">{isLoading ? <tr><td colSpan={7} className="px-5 py-12 text-center text-slate-400">Carregando histórico...</td></tr> : data.length === 0 ? <tr><td colSpan={7} className="px-5 py-14 text-center"><div className="mx-auto grid h-10 w-10 place-items-center rounded-xl bg-slate-100"><EmptyIcon className="h-5 w-5 text-slate-400"/></div><p className="mt-3 font-medium text-slate-600">Nenhum registro encontrado</p><p className="mt-1 text-xs text-slate-400">Use O.S. ou serial para refinar a pesquisa.</p></td></tr> : data.map((call: any) => <tr key={call.id} className="hover:bg-slate-50"><td className="px-5 py-4 font-mono font-semibold text-slate-900">{call.numeroOs}</td><td className="px-5 py-4 font-mono text-xs text-slate-600">{call.serial}</td><td className="px-5 py-4 text-slate-700">{call.modelo}</td><td className="max-w-[320px] px-5 py-4 text-slate-600">{call.queixa}</td><td className="whitespace-nowrap px-5 py-4 text-xs text-slate-500">{new Date(call.dataEntrada).toLocaleDateString()}</td><td className="whitespace-nowrap px-5 py-4 text-xs text-slate-500">{call.dataMovimento ? new Date(call.dataMovimento).toLocaleString() : "—"}</td><td className="px-5 py-4"><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold text-slate-600">{call.origem || "—"}</span></td></tr>)}</tbody></table></div></div></div></div>;
}
