import { useAuth } from "@/_core/hooks/useAuth";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, Pencil, Plus, Search, Trash2, XCircle } from "lucide-react";
import React, { useMemo, useState } from "react";
import { toast } from "sonner";
import { useLocation } from "wouter";

type CatalogForm = { modelo: string; marca: string; tipo: "IMAGEM" | "BIOS"; versao: string; ativo: boolean; observacao: string };
const emptyForm = (): CatalogForm => ({ modelo: "", marca: "", tipo: "IMAGEM", versao: "", ativo: true, observacao: "" });

export default function ImageBiosSettings() {
  const { user } = useAuth();
  const canManage = user?.role === "admin" || user?.role === "manager";
  const [, setLocation] = useLocation();
  const utils = trpc.useUtils();
  const [search, setSearch] = useState("");
  const [form, setForm] = useState<CatalogForm>(emptyForm);
  const [editingId, setEditingId] = useState<number | null>(null);
  const [deleteId, setDeleteId] = useState<number | null>(null);
  const input = useMemo(() => ({ search }), [search]);
  const { data: entries = [], isLoading } = trpc.imageBios.list.useQuery(input, { enabled: canManage });
  const refresh = () => utils.imageBios.list.invalidate();
  const create = trpc.imageBios.create.useMutation({ onSuccess: () => { toast.success("Versão cadastrada"); setForm(emptyForm()); refresh(); }, onError: (error) => toast.error(error.message) });
  const update = trpc.imageBios.update.useMutation({ onSuccess: () => { toast.success("Versão atualizada"); setEditingId(null); setForm(emptyForm()); refresh(); }, onError: (error) => toast.error(error.message) });
  const remove = trpc.imageBios.delete.useMutation({ onSuccess: () => { toast.success("Cadastro excluído"); setDeleteId(null); refresh(); }, onError: (error) => toast.error(error.message) });
  const submit = () => { if (editingId) update.mutate({ id: editingId, ...form }); else create.mutate(form); };
  const edit = (item: any) => { setEditingId(item.id); setForm({ modelo: item.modelo, marca: item.marca, tipo: item.tipo, versao: item.versao, ativo: item.ativo, observacao: item.observacao || "" }); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const toggleActive = (item: any) => update.mutate({ id: item.id, modelo: item.modelo, marca: item.marca, tipo: item.tipo, versao: item.versao, ativo: !item.ativo, observacao: item.observacao || "" });

  if (!canManage) return <div className="p-6 lg:p-8"><section className="mx-auto max-w-xl rounded-2xl border border-amber-200 bg-amber-50 p-8 text-center"><XCircle className="mx-auto h-8 w-8 text-amber-600"/><h1 className="mt-3 text-xl font-bold text-slate-900">Área restrita</h1><p className="mt-2 text-sm text-slate-600">Somente Owner e Gestor podem gerenciar a base de Imagens/BIOS.</p><Button className="mt-5 bg-[#2E7D32] text-white hover:bg-[#0D1117]" onClick={() => setLocation("/configuracoes")}>Voltar para Configurações</Button></section></div>;

  return <div className="p-6 lg:p-8"><div className="mx-auto max-w-6xl"><p className="text-sm font-medium text-[#2E7D32]">Base técnica</p><div className="mt-1 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-bold text-slate-900">Imagens / BIOS</h1><p className="mt-1 text-sm text-slate-500">Cadastre as versões usadas na resolução automática pelo modelo do chamado.</p></div><Button variant="outline" className="border-[#2E7D32] text-[#2E7D32]" onClick={() => setLocation("/configuracoes")}>Voltar para Configurações</Button></div>
    <section className="mt-7 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex items-center justify-between gap-3"><div><h2 className="font-semibold text-slate-900">{editingId ? "Editar versão" : "Cadastrar versão"}</h2><p className="mt-1 text-sm text-slate-500">A versão será usada automaticamente para modelos ativos correspondentes.</p></div>{editingId && <Button size="sm" variant="outline" onClick={() => { setEditingId(null); setForm(emptyForm()); }}>Cancelar edição</Button>}</div><div className="mt-5 grid gap-3 md:grid-cols-2"><Input aria-label="Modelo" placeholder="Modelo *" value={form.modelo} onChange={(event) => setForm({ ...form, modelo: event.target.value })}/><Input aria-label="Marca" placeholder="Marca *" value={form.marca} onChange={(event) => setForm({ ...form, marca: event.target.value })}/><select aria-label="Tipo" className="h-9 rounded-md border border-slate-200 bg-white px-3 text-sm text-slate-800" value={form.tipo} onChange={(event) => setForm({ ...form, tipo: event.target.value as "IMAGEM" | "BIOS" })}><option value="IMAGEM">IMAGEM</option><option value="BIOS">BIOS</option></select><label className="flex items-center gap-3 rounded-md border border-slate-200 px-3 text-sm text-slate-700"><input type="checkbox" checked={form.ativo} onChange={(event) => setForm({ ...form, ativo: event.target.checked })} className="accent-[#2E7D32]"/>Ativo para resolução automática</label></div><Textarea aria-label="Versão Imagem BIOS" className="mt-3" placeholder="Versão Imagem/BIOS *" value={form.versao} onChange={(event) => setForm({ ...form, versao: event.target.value })}/><Textarea aria-label="Observação" className="mt-3" placeholder="Observação" value={form.observacao} onChange={(event) => setForm({ ...form, observacao: event.target.value })}/><Button className="mt-4 bg-[#2E7D32] text-white hover:bg-[#0D1117]" disabled={!form.modelo.trim() || !form.marca.trim() || !form.versao.trim() || create.isPending || update.isPending} onClick={submit}>{editingId ? update.isPending ? "Salvando..." : "Salvar alteração" : create.isPending ? "Cadastrando..." : <><Plus className="mr-2 h-4 w-4"/>Cadastrar versão</>}</Button></section>
    <section className="mt-6 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-wrap items-center justify-between gap-4 border-b border-slate-200 p-5"><div><h2 className="font-semibold text-slate-900">Modelos cadastrados</h2><p className="mt-1 text-sm text-slate-500">{entries.length} registro(s) encontrado(s). Use o status para ativar ou desativar rapidamente.</p></div><div className="relative w-full max-w-sm"><Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-400"/><Input aria-label="Pesquisar modelo" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Pesquisar modelo, marca ou versão" className="pl-9"/></div></div><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wider text-slate-500"><tr><th className="px-5 py-3">Modelo</th><th className="px-5 py-3">Marca</th><th className="px-5 py-3">Tipo</th><th className="px-5 py-3">Versão Imagem/BIOS</th><th className="px-5 py-3">Ativo</th><th className="px-5 py-3 text-right">Ações</th></tr></thead><tbody>{isLoading ? <tr><td colSpan={6} className="px-5 py-8 text-center text-slate-500">Carregando base técnica...</td></tr> : entries.length === 0 ? <tr><td colSpan={6} className="px-5 py-8 text-center text-slate-500">Nenhum modelo encontrado.</td></tr> : entries.map((item) => <tr key={item.id} className="border-t border-slate-100 align-top"><td className="px-5 py-4 font-medium text-slate-900">{item.modelo}{item.observacao && <p className="mt-1 max-w-xs text-xs font-normal text-slate-500">{item.observacao}</p>}</td><td className="px-5 py-4 text-slate-700">{item.marca}</td><td className="px-5 py-4"><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-semibold text-slate-700">{item.tipo}</span></td><td className="max-w-md whitespace-pre-wrap px-5 py-4 font-mono text-xs text-slate-700">{item.versao}</td><td className="px-5 py-4"><Button size="sm" variant="outline" disabled={update.isPending} className={item.ativo ? "border-emerald-200 text-emerald-700 hover:bg-emerald-50" : "border-slate-300 text-slate-500 hover:bg-slate-50"} onClick={() => toggleActive(item)}>{item.ativo ? <><CheckCircle2 className="mr-1 h-3.5 w-3.5"/>Ativo</> : "Inativo"}</Button></td><td className="px-5 py-4"><div className="flex justify-end gap-2"><Button size="sm" variant="outline" onClick={() => edit(item)}><Pencil className="mr-1 h-3.5 w-3.5"/>Editar</Button><Button size="sm" variant="outline" className="border-red-200 text-red-700 hover:bg-red-50 hover:text-red-800" onClick={() => setDeleteId(item.id)}><Trash2 className="mr-1 h-3.5 w-3.5"/>Excluir</Button></div></td></tr>)}</tbody></table></div></section>
    <AlertDialog open={deleteId !== null} onOpenChange={(open) => { if (!open) setDeleteId(null); }}><AlertDialogContent className="bg-white text-slate-900"><AlertDialogHeader><AlertDialogTitle>Excluir cadastro?</AlertDialogTitle><AlertDialogDescription>Esta versão deixará de ser usada na resolução automática pelo modelo.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancelar</AlertDialogCancel><AlertDialogAction className="bg-red-700 text-white hover:bg-red-800" onClick={() => deleteId !== null && remove.mutate({ id: deleteId })}>Excluir</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </div></div>;
}
