import { jsPDF } from "jspdf";
import React from "react";

export type LaudoVisualData = {
  numeroChamado: string; dataEmissao?: string; marca: string; nomeCliente: string; contato: string; enderecoCliente: string; cidadeCliente: string; estadoCliente: string; produto: string; tipoProduto: string; numeroSerie: string; bilheteSeguro: string; defeitoReclamado: string; avaliacaoTecnica: string; conclusao: string; responsavelTecnico: string; fotos: string[];
};

export type LaudoLogos = { logoPositivo?: string | null; logoInfinix?: string | null; logoVaio?: string | null; logoCompaq?: string | null } | null | undefined;

const logoItems = (logos: LaudoLogos) => [["Positivo", logos?.logoPositivo], ["Infinix", logos?.logoInfinix], ["Vaio", logos?.logoVaio], ["Compaq", logos?.logoCompaq]] as const;
const issuedAt = (data?: string) => data ? data.split("-").reverse().join("/") : "—";

function DocumentHeader({ data, logos, label }: { data: LaudoVisualData; logos: LaudoLogos; label: string }) {
  return <header className="border-b-2 border-[#2E7D32] pb-3"><div className="grid grid-cols-[1fr_148px] items-start gap-2"><div className="text-[9px] leading-[1.35] text-slate-700"><p className="font-bold text-[11px] text-slate-900">Positivo Tecnologia</p><p>CNPJ: 81.243.735/0019-77</p><p>Rua João Bettega, 5200 - Cidade Industrial</p><p>Curitiba - PR</p><p className="mt-px">Tel: (41) 3316-7500</p></div><div className="grid grid-cols-2 gap-1">{logoItems(logos).map(([brand, url]) => <div key={brand} className="flex h-7 items-center justify-center overflow-hidden">{url ? <img src={url} alt={`Logo ${brand}`} className="max-h-6 max-w-full object-contain"/> : <span className="text-center text-[7px] font-bold uppercase tracking-wide text-slate-400">{brand}</span>}</div>)}</div></div><div className="mt-3 text-center"><h1 className="text-[16px] font-bold tracking-[0.04em] text-slate-900">{label} - Nº {data.numeroChamado}</h1><p className="mt-1 text-[9px] text-slate-600">Data de Emissão: {issuedAt(data.dataEmissao)}</p></div></header>;
}

function DocumentSection({ label, title, children }: { label: string; title: string; children: React.ReactNode }) {
  return <section className="border border-slate-200"><div className="flex items-center gap-2 border-b border-slate-200 bg-slate-50 px-4 py-2"><span className="font-mono text-[9px] font-bold tracking-[0.16em] text-[#2E7D32]">{label}</span><h2 className="text-[10px] font-bold tracking-[0.1em] text-slate-800">{title}</h2></div><div className="p-4">{children}</div></section>;
}

function DocumentField({ label, value, wide }: { label: string; value?: string; wide?: boolean }) {
  return <div className={wide ? "col-span-2" : ""}><p className="text-[8px] font-bold uppercase tracking-[0.12em] text-slate-400">{label}</p><p className="mt-1 min-h-4 text-[10px] font-medium leading-snug text-slate-800">{value || "—"}</p></div>;
}

function PageNumber({ current }: { current: number }) { return <p className="mt-3 text-right text-[8px] font-semibold uppercase tracking-[0.12em] text-slate-500">Página {current} de 2</p>; }

export function LaudoDocument({ data, logos, documentRef }: { data: LaudoVisualData; logos: LaudoLogos; documentRef?: React.RefObject<HTMLDivElement | null> }) {
  return <div><article ref={documentRef} className="mx-auto w-[794px] bg-white p-[42px] text-slate-900" style={{ fontFamily: "Arial, Helvetica, sans-serif" }}><DocumentHeader data={data} logos={logos} label="LAUDO TÉCNICO"/><main className="mt-5 space-y-4"><DocumentSection label="01" title="IDENTIFICAÇÃO DO CLIENTE"><div className="grid grid-cols-2 gap-x-8 gap-y-3"><DocumentField label="Nome" value={data.nomeCliente}/><DocumentField label="Contato" value={data.contato}/><DocumentField label="Endereço" value={data.enderecoCliente} wide/><DocumentField label="Cidade / UF" value={`${data.cidadeCliente}${data.estadoCliente ? ` / ${data.estadoCliente}` : ""}`} wide/></div></DocumentSection><DocumentSection label="02" title="IDENTIFICAÇÃO DO PRODUTO"><div className="grid grid-cols-3 gap-x-6 gap-y-3"><DocumentField label="Marca" value={data.marca}/><DocumentField label="Produto" value={data.produto}/><DocumentField label="Tipo" value={data.tipoProduto}/><DocumentField label="Número de série" value={data.numeroSerie}/><DocumentField label="Bilhete de seguro" value={data.bilheteSeguro}/><DocumentField label="Nº do chamado" value={data.numeroChamado}/></div></DocumentSection><DocumentSection label="03" title="AVALIAÇÃO TÉCNICA"><div className="space-y-4"><div><p className="text-[8px] font-bold uppercase tracking-[0.12em] text-slate-400">Defeito reclamado</p><p className="mt-1 whitespace-pre-wrap text-[10px] leading-relaxed text-slate-800">{data.defeitoReclamado || "—"}</p></div><div className="border-t border-slate-100 pt-3"><p className="text-[8px] font-bold uppercase tracking-[0.12em] text-slate-400">Avaliação técnica</p><p className="mt-1 whitespace-pre-wrap text-[10px] leading-relaxed text-slate-800">{data.avaliacaoTecnica || "—"}</p></div><div className="border-t border-slate-100 pt-3"><p className="text-[8px] font-bold uppercase tracking-[0.12em] text-slate-400">Conclusão</p><p className="mt-1 whitespace-pre-wrap text-[10px] font-semibold leading-relaxed text-slate-800">{data.conclusao || "—"}</p></div></div></DocumentSection></main><footer className="mt-9 flex justify-end border-t border-slate-300 pt-4"><div className="w-56 border-t border-slate-500 pt-2 text-center"><p className="text-[10px] font-bold text-slate-800">{data.responsavelTecnico}</p><p className="mt-0.5 text-[8px] uppercase tracking-[0.12em] text-slate-400">Responsável técnico</p></div></footer><PageNumber current={1}/></article></div>;
}

export function LaudoPhotoPagePreview({ data, logos }: { data: LaudoVisualData; logos: LaudoLogos }) {
  return <article className="mx-auto w-[794px] bg-white p-[42px] text-slate-900" style={{ fontFamily: "Arial, Helvetica, sans-serif" }}><DocumentHeader data={data} logos={logos} label="REGISTRO FOTOGRÁFICO"/><main className="mt-5 grid grid-cols-2 gap-4">{data.fotos.map((photo, index) => <figure key={`${photo}-${index}`} className="overflow-hidden border border-slate-300 bg-slate-50 p-2"><div className="flex h-48 items-center justify-center bg-white"><img src={photo} alt={`Evidência ${index + 1}`} className="max-h-full max-w-full object-contain"/></div><figcaption className="mt-2 text-[9px] font-bold tracking-[0.1em] text-[#173F5F]">EVIDÊNCIA {String(index + 1).padStart(2, "0")}</figcaption></figure>)}</main><PageNumber current={2}/></article>;
}

function imageFormat(source: string) { return /^data:image\/png/i.test(source) ? "PNG" : "JPEG"; }
function drawPdfImage(pdf: jsPDF, source: string, x: number, y: number, maxWidth: number, maxHeight: number) { const props = pdf.getImageProperties(source); const scale = Math.min(maxWidth / props.width, maxHeight / props.height); const width = props.width * scale; const height = props.height * scale; pdf.addImage(source, imageFormat(source), x + (maxWidth - width) / 2, y + (maxHeight - height) / 2, width, height); }
function drawPdfHeader(pdf: jsPDF, data: LaudoVisualData, logos: LaudoLogos, pageLabel: string, currentPage: number) { pdf.setTextColor(15, 23, 42); pdf.setFont("helvetica", "bold"); pdf.setFontSize(9); pdf.text("Positivo Tecnologia", 14, 13); pdf.setFont("helvetica", "normal"); pdf.setFontSize(7); pdf.text(["CNPJ: 81.243.735/0019-77", "Rua João Bettega, 5200 - Cidade Industrial", "Curitiba - PR", "Tel: (41) 3316-7500"], 14, 17.2); pdf.setFont("helvetica", "bold"); pdf.setFontSize(10); pdf.text(`${pageLabel} - Nº ${data.numeroChamado}`, 104, 14, { align: "center" }); pdf.setFont("helvetica", "normal"); pdf.setFontSize(7); pdf.text(`Data de Emissão: ${issuedAt(data.dataEmissao)}`, 104, 19, { align: "center" }); logoItems(logos).forEach(([, source], index) => { if (!source?.startsWith("data:image/")) return; const x = 169 + (index % 2) * 13; const y = 8 + Math.floor(index / 2) * 8; drawPdfImage(pdf, source, x, y, 11, 6); }); pdf.setDrawColor(46, 125, 50); pdf.line(14, 27, 196, 27); pdf.setTextColor(71, 85, 105); pdf.setFontSize(7); pdf.text(`PÁGINA ${currentPage} DE 2`, 196, 32, { align: "right" }); }
function sectionTitle(pdf: jsPDF, number: string, title: string, y: number) { pdf.setDrawColor(203, 213, 225); pdf.setFillColor(248, 250, 252); pdf.rect(14, y, 182, 7, "FD"); pdf.setTextColor(46, 125, 50); pdf.setFont("helvetica", "bold"); pdf.setFontSize(7); pdf.text(number, 18, y + 4.6); pdf.setTextColor(30, 41, 59); pdf.text(title, 29, y + 4.6); return y + 11; }
function field(pdf: jsPDF, label: string, value: string, x: number, y: number, width: number) { pdf.setTextColor(148, 163, 184); pdf.setFont("helvetica", "bold"); pdf.setFontSize(6); pdf.text(label.toUpperCase(), x, y); pdf.setTextColor(30, 41, 59); pdf.setFont("helvetica", "normal"); pdf.setFontSize(8); const lines = pdf.splitTextToSize(value || "—", width); pdf.text(lines, x, y + 4); return Math.max(9, lines.length * 3.4 + 5); }
function paragraph(pdf: jsPDF, label: string, value: string, y: number) { pdf.setTextColor(148, 163, 184); pdf.setFont("helvetica", "bold"); pdf.setFontSize(6); pdf.text(label.toUpperCase(), 18, y); pdf.setTextColor(30, 41, 59); pdf.setFont("helvetica", "normal"); pdf.setFontSize(8); const lines = pdf.splitTextToSize(value || "—", 164); pdf.text(lines, 18, y + 4); return Math.max(12, lines.length * 3.5 + 7); }

export function buildLaudoPdf(data: LaudoVisualData, logos: LaudoLogos) { const pdf = new jsPDF("p", "mm", "a4"); drawPdfHeader(pdf, data, logos, "LAUDO TÉCNICO", 1); let y = 36; y = sectionTitle(pdf, "01", "IDENTIFICAÇÃO DO CLIENTE", y); const clientRowOne = Math.max(field(pdf, "Nome", data.nomeCliente, 18, y, 76), field(pdf, "Contato", data.contato, 108, y, 70)); y += clientRowOne; y += field(pdf, "Endereço", data.enderecoCliente, 18, y, 160); y += field(pdf, "Cidade / UF", `${data.cidadeCliente}${data.estadoCliente ? ` / ${data.estadoCliente}` : ""}`, 18, y, 160) + 3; y = sectionTitle(pdf, "02", "IDENTIFICAÇÃO DO PRODUTO", y); const productRowOne = Math.max(field(pdf, "Marca", data.marca, 18, y, 47), field(pdf, "Produto", data.produto, 78, y, 47), field(pdf, "Tipo", data.tipoProduto, 138, y, 40)); y += productRowOne; const productRowTwo = Math.max(field(pdf, "Número de série", data.numeroSerie, 18, y, 47), field(pdf, "Bilhete de seguro", data.bilheteSeguro, 78, y, 47), field(pdf, "Nº do chamado", data.numeroChamado, 138, y, 40)); y += productRowTwo + 3; y = sectionTitle(pdf, "03", "AVALIAÇÃO TÉCNICA", y); y += paragraph(pdf, "Defeito reclamado", data.defeitoReclamado, y); y += paragraph(pdf, "Avaliação técnica", data.avaliacaoTecnica, y); y += paragraph(pdf, "Conclusão", data.conclusao, y); const signatureY = Math.min(Math.max(y + 16, 245), 267); pdf.setDrawColor(100, 116, 139); pdf.line(132, signatureY, 188, signatureY); pdf.setTextColor(30, 41, 59); pdf.setFont("helvetica", "bold"); pdf.setFontSize(8); pdf.text(data.responsavelTecnico || "—", 160, signatureY + 5, { align: "center" }); pdf.setTextColor(148, 163, 184); pdf.setFont("helvetica", "normal"); pdf.setFontSize(6); pdf.text("RESPONSÁVEL TÉCNICO", 160, signatureY + 9, { align: "center" }); pdf.addPage(); drawPdfHeader(pdf, data, logos, "REGISTRO FOTOGRÁFICO", 2); const positions = [[14, 36], [108, 36], [14, 153], [108, 153]] as const; data.fotos.forEach((photo, index) => { if (!photo.startsWith("data:image/")) throw new Error(`A foto ${index + 1} não foi preparada para o PDF.`); const [x, yPosition] = positions[index]; pdf.setFillColor(248, 250, 252); pdf.setDrawColor(203, 213, 225); pdf.rect(x, yPosition, 84, 101, "FD"); drawPdfImage(pdf, photo, x + 2, yPosition + 2, 80, 91); pdf.setTextColor(23, 63, 95); pdf.setFont("helvetica", "bold"); pdf.setFontSize(8); pdf.text(`EVIDÊNCIA ${String(index + 1).padStart(2, "0")}`, x + 4, yPosition + 98); }); pdf.setDrawColor(203, 213, 225); pdf.line(14, 286, 196, 286); pdf.setTextColor(100, 116, 139); pdf.setFont("helvetica", "normal"); pdf.setFontSize(7); pdf.text("Laudo técnico • Registro fotográfico", 14, 290); pdf.text("Página 2 de 2", 196, 290, { align: "right" }); return pdf; }

export async function createLaudoPdfPreviewUrl(data: LaudoVisualData, logos: LaudoLogos) { return URL.createObjectURL(buildLaudoPdf(data, logos).output("blob")); }
export async function generateLaudoPdf(data: LaudoVisualData, logos: LaudoLogos, _documentRef?: React.RefObject<HTMLDivElement | null>) { const pdf = buildLaudoPdf(data, logos); const url = URL.createObjectURL(pdf.output("blob")); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `Laudo_${data.numeroChamado}.pdf`; anchor.style.display = "none"; document.body.appendChild(anchor); anchor.click(); anchor.remove(); window.setTimeout(() => URL.revokeObjectURL(url), 1000); }
